export const topics = [
  { id: 'sanitation', label: 'Sanitation & safety', count: 8, icon: '✦', color: 'coral' },
  { id: 'hair', label: 'Hair & scalp', count: 8, icon: '⌁', color: 'green' },
  { id: 'chemistry', label: 'Chemical services', count: 8, icon: '◌', color: 'yellow' },
  { id: 'skin', label: 'Skin & nails', count: 8, icon: '✧', color: 'blue' },
  { id: 'nebraska', label: 'Nebraska rules', count: 8, icon: '§', color: 'pink' },
];

export const questions = [
  {
    id: 1,
    topic: 'sanitation',
    prompt: 'What is the first step before disinfecting a reusable implement?',
    choices: ['Spray it with disinfectant', 'Remove visible debris and clean it', 'Place it in a UV sanitizer', 'Dry it with a towel'],
    answer: 1,
    explanation: 'Cleaning removes visible debris and allows the disinfectant to work effectively. Follow the product label for contact time.',
    difficulty: 'Core',
  },
  {
    id: 2,
    topic: 'sanitation',
    prompt: 'Which item should be discarded after one use?',
    choices: ['Metal cuticle pusher', 'Glass nail file', 'Porous orangewood stick', 'Stainless steel shears'],
    answer: 2,
    explanation: 'Porous items cannot be reliably cleaned and disinfected, so they are single-use and must be discarded after service.',
    difficulty: 'Core',
  },
  {
    id: 3,
    topic: 'hair',
    prompt: 'The hair’s natural wave pattern is primarily determined by the shape of the:',
    choices: ['Medulla', 'Follicle', 'Cuticle', 'Sebaceous gland'],
    answer: 1,
    explanation: 'The shape of the follicle influences whether hair grows straight, wavy, or curly.',
    difficulty: 'Core',
  },
  {
    id: 4,
    topic: 'hair',
    prompt: 'What is the safest response when a client shows signs of a contagious scalp condition?',
    choices: ['Proceed with a shorter service', 'Apply oil and continue', 'Stop and recommend medical evaluation', 'Use extra-hot water'],
    answer: 2,
    explanation: 'A suspected contagious condition is a contraindication. Stop the service, protect yourself and others, and refer the client to a physician.',
    difficulty: 'Clinical',
  },
  {
    id: 5,
    topic: 'chemistry',
    prompt: 'A strand test is performed primarily to determine the:',
    choices: ['Client’s face shape', 'Processing result and timing', 'Density of the scalp', 'Best retail product'],
    answer: 0,
    explanation: 'A strand test previews the result and helps determine how the hair will respond before a full chemical service.',
    difficulty: 'Core',
  },
  {
    id: 6,
    topic: 'chemistry',
    prompt: 'Which product changes the natural color of hair by diffusing natural pigment?',
    choices: ['Temporary rinse', 'Permanent color', 'Shampoo', 'Finishing spray'],
    answer: 1,
    explanation: 'Permanent color uses alkalinity and oxidation to lift or deposit color, changing the hair’s natural pigment.',
    difficulty: 'Core',
  },
  {
    id: 7,
    topic: 'skin',
    prompt: 'What should happen before performing a facial massage?',
    choices: ['Apply product appropriate for the client’s skin', 'Use a strong exfoliant', 'Turn off all ventilation', 'Cover the eyes with cotton only'],
    answer: 0,
    explanation: 'Use a suitable lubricant or massage product after cleansing and skin analysis. Adjust the service for sensitivities and contraindications.',
    difficulty: 'Core',
  },
  {
    id: 8,
    topic: 'skin',
    prompt: 'The nail plate is made primarily of:',
    choices: ['Collagen', 'Keratin', 'Melanin', 'Sebum'],
    answer: 1,
    explanation: 'The nail plate is composed primarily of hard, translucent keratinized cells.',
    difficulty: 'Core',
  },
  {
    id: 9,
    topic: 'nebraska',
    prompt: 'Where should a candidate verify current Nebraska licensing requirements and rules?',
    choices: ['An old school handout', 'A social media post', 'Nebraska DHHS', 'A product distributor'],
    answer: 2,
    explanation: 'Nebraska Department of Health and Human Services is the authoritative source for current state licensing requirements and regulations.',
    difficulty: 'Nebraska',
  },
  {
    id: 10,
    topic: 'nebraska',
    prompt: 'Why should Nebraska-law flashcards include a review date?',
    choices: ['Rules and exam bulletins can change', 'It changes the correct answer', 'It makes the card longer', 'It replaces source checking'],
    answer: 0,
    explanation: 'Licensing rules and exam procedures can be amended. Keep state-specific study content dated and verify it against current DHHS and exam bulletins.',
    difficulty: 'Nebraska',
  },
  {
    id: 11,
    topic: 'sanitation',
    prompt: 'What should you do with a reusable implement immediately after a service?',
    choices: ['Put it back in the drawer', 'Place it in a labeled closed container for cleaning', 'Wipe it on a towel', 'Leave it on the workstation'],
    answer: 1,
    explanation: 'Keep used implements separate from clean items and place them in a labeled container until they can be cleaned and disinfected.',
    difficulty: 'Core',
  },
  {
    id: 12,
    topic: 'sanitation',
    prompt: 'What is the best way to prevent cross-contamination during a service?',
    choices: ['Reuse towels if they look clean', 'Keep clean and used supplies separate', 'Store tools in an open sink', 'Use the same applicator for every client'],
    answer: 1,
    explanation: 'Separate clean supplies from used items, change linens between clients, and use clean or single-use applicators as required.',
    difficulty: 'Core',
  },
  {
    id: 13,
    topic: 'sanitation',
    prompt: 'Why should a disinfectant be mixed according to its label?',
    choices: ['To make it smell stronger', 'To ensure the correct strength and contact time', 'To make tools dry faster', 'To replace cleaning'],
    answer: 1,
    explanation: 'The label provides the required concentration and contact time. Incorrect mixing may make the product ineffective or unsafe.',
    difficulty: 'Core',
  },
  {
    id: 14,
    topic: 'sanitation',
    prompt: 'Which item is normally single-use because it is porous?',
    choices: ['Metal comb', 'Stainless steel clipper', 'Wooden spatula', 'Glass bowl'],
    answer: 2,
    explanation: 'Porous items can absorb product and microorganisms, so disposable wooden applicators should not be reused.',
    difficulty: 'Core',
  },
  {
    id: 15,
    topic: 'sanitation',
    prompt: 'When should a cosmetologist wash their hands?',
    choices: ['Only at the start of the day', 'Before and after each client service', 'Only after using chemicals', 'Only when gloves tear'],
    answer: 1,
    explanation: 'Handwashing before and after each service helps protect both the client and the cosmetologist.',
    difficulty: 'Core',
  },
  {
    id: 16,
    topic: 'sanitation',
    prompt: 'What should happen if blood exposure occurs during a service?',
    choices: ['Continue and clean up later', 'Stop, protect yourself, and follow the exposure procedure', 'Cover it with makeup', 'Rinse the tool and keep using it'],
    answer: 1,
    explanation: 'Stop the service, use appropriate protective measures, dispose of contaminated materials, and follow the required exposure-control procedure.',
    difficulty: 'Clinical',
  },
  {
    id: 17,
    topic: 'hair',
    prompt: 'Which layer of the hair shaft provides most of its strength and elasticity?',
    choices: ['Cuticle', 'Cortex', 'Medulla', 'Follicle'],
    answer: 1,
    explanation: 'The cortex makes up most of the hair shaft and contains the keratin fibers responsible for strength, elasticity, and pigment.',
    difficulty: 'Core',
  },
  {
    id: 18,
    topic: 'hair',
    prompt: 'What does hair porosity describe?',
    choices: ['The hair length', 'The hair ability to absorb and retain moisture', 'The number of hairs per square inch', 'The natural curl pattern'],
    answer: 1,
    explanation: 'Porosity is the hair ability to absorb and retain moisture. The condition of the cuticle affects porosity.',
    difficulty: 'Core',
  },
  {
    id: 19,
    topic: 'hair',
    prompt: 'Which tool is designed to remove bulk from the hair?',
    choices: ['Razor comb or texturizing shears', 'Tail comb', 'Neck duster', 'Shampoo brush'],
    answer: 0,
    explanation: 'Texturizing shears and razor tools can remove weight or create texture when used with the correct technique.',
    difficulty: 'Core',
  },
  {
    id: 20,
    topic: 'hair',
    prompt: 'What is the purpose of a client consultation before a haircut?',
    choices: ['Choose the fastest service', 'Understand goals, hair history, and limitations', 'Avoid discussing maintenance', 'Guarantee an identical reference photo'],
    answer: 1,
    explanation: 'A consultation establishes the client goals, hair history, lifestyle, and realistic result before the service begins.',
    difficulty: 'Core',
  },
  {
    id: 21,
    topic: 'hair',
    prompt: 'What protects the client from heat during a blow-dry or iron service?',
    choices: ['Higher heat', 'Heat-protective product and appropriate temperature', 'Wet hair only', 'Extra hairspray'],
    answer: 1,
    explanation: 'Use a heat protectant and select a temperature appropriate for the hair condition and the tool being used.',
    difficulty: 'Core',
  },
  {
    id: 22,
    topic: 'hair',
    prompt: 'What is the primary purpose of the hair cuticle?',
    choices: ['Produce melanin', 'Protect the inner layers of the hair shaft', 'Create sebum', 'Attach the hair to the muscle'],
    answer: 1,
    explanation: 'The cuticle is the outer protective layer of overlapping cells that helps protect the cortex and medulla.',
    difficulty: 'Core',
  },
  {
    id: 23,
    topic: 'chemistry',
    prompt: 'What does a patch test help identify before certain color services?',
    choices: ['Hair density', 'Possible skin sensitivity to the product', 'The final haircut shape', 'The client face shape'],
    answer: 1,
    explanation: 'A patch test can help identify a possible allergic sensitivity. Follow the product directions and applicable rules.',
    difficulty: 'Safety',
  },
  {
    id: 24,
    topic: 'chemistry',
    prompt: 'What is the purpose of a neutralizer in a permanent wave?',
    choices: ['Reform and stabilize the bonds in the new shape', 'Lighten the natural pigment', 'Clean the scalp', 'Add shampoo fragrance'],
    answer: 0,
    explanation: 'The neutralizer reforms and stabilizes the bonds after the hair has been softened and wrapped into its new shape.',
    difficulty: 'Core',
  },
  {
    id: 25,
    topic: 'chemistry',
    prompt: 'Why should chemical products never be combined unless the label says to do so?',
    choices: ['They may react unpredictably', 'They always become weaker', 'They will turn into shampoo', 'They cannot be stored afterward'],
    answer: 0,
    explanation: 'Unapproved combinations can create dangerous reactions, fumes, heat, or an ineffective product. Follow manufacturer directions.',
    difficulty: 'Safety',
  },
  {
    id: 26,
    topic: 'chemistry',
    prompt: 'What does developer primarily provide in oxidative hair color?',
    choices: ['Moisture only', 'Oxidation needed to activate the color', 'A temporary styling hold', 'A cleansing action'],
    answer: 1,
    explanation: 'Developer supplies the oxidation needed to activate many permanent and demi-permanent color formulas.',
    difficulty: 'Core',
  },
  {
    id: 27,
    topic: 'chemistry',
    prompt: 'What should you do if a client reports severe burning during a chemical service?',
    choices: ['Add more product', 'Stop the service and rinse according to product directions', 'Cover the area with a towel', 'Wait until processing is complete'],
    answer: 1,
    explanation: 'Severe burning is not a normal reaction. Stop immediately and follow the product safety directions, including rinsing when directed.',
    difficulty: 'Safety',
  },
  {
    id: 28,
    topic: 'chemistry',
    prompt: 'What is a client record useful for during chemical services?',
    choices: ['Tracking formulas, dates, and reactions', 'Replacing a consultation', 'Guaranteeing the same result on every head', 'Avoiding strand tests forever'],
    answer: 0,
    explanation: 'Accurate records help track formulas, processing details, results, and any reactions that may affect future services.',
    difficulty: 'Core',
  },
  {
    id: 29,
    topic: 'skin',
    prompt: 'What is the purpose of cleansing the skin before a facial?',
    choices: ['Remove surface impurities and prepare the skin', 'Close every pore permanently', 'Replace skin analysis', 'Increase irritation'],
    answer: 0,
    explanation: 'Cleansing removes surface makeup, oil, and debris so the skin can be properly analyzed and treated.',
    difficulty: 'Core',
  },
  {
    id: 30,
    topic: 'skin',
    prompt: 'Which condition is a reason to postpone waxing?',
    choices: ['Healthy skin', 'Open wound or active irritation in the area', 'Normal skin texture', 'A recent consultation'],
    answer: 1,
    explanation: 'Waxing irritated or broken skin can cause additional injury. Postpone the service until the area has healed.',
    difficulty: 'Safety',
  },
  {
    id: 31,
    topic: 'skin',
    prompt: 'What is the function of sebum?',
    choices: ['Lubricate and help protect the skin and hair', 'Form the nail plate', 'Remove all bacteria', 'Produce sweat only'],
    answer: 0,
    explanation: 'Sebum is an oily secretion from sebaceous glands that helps lubricate and protect the skin and hair.',
    difficulty: 'Core',
  },
  {
    id: 32,
    topic: 'skin',
    prompt: 'What should be used to protect a client eyes during a facial service?',
    choices: ['A sharp tool', 'Appropriate eye protection or coverings', 'Strong exfoliant', 'Unlabeled product'],
    answer: 1,
    explanation: 'Use clean, appropriate eye coverings or protection and keep products away from the eyes unless specifically intended for that area.',
    difficulty: 'Core',
  },
  {
    id: 33,
    topic: 'skin',
    prompt: 'What is the nail matrix responsible for?',
    choices: ['Producing much of the nail plate', 'Polishing the free edge', 'Storing polish', 'Removing cuticle oil'],
    answer: 0,
    explanation: 'The matrix contains cells that produce much of the nail plate, so injury to it can affect nail growth.',
    difficulty: 'Core',
  },
  {
    id: 34,
    topic: 'skin',
    prompt: 'What is the safest response to a suspected fungal nail infection?',
    choices: ['Cover it with polish', 'Perform the service quickly', 'Decline the service and recommend medical evaluation', 'File until the discoloration is gone'],
    answer: 2,
    explanation: 'A suspected infection is a contraindication. Do not diagnose or treat it; recommend evaluation by an appropriate medical professional.',
    difficulty: 'Clinical',
  },
  {
    id: 35,
    topic: 'nebraska',
    prompt: 'Which examination is required for an initial Nebraska cosmetology license?',
    choices: ['The NIC written examination', 'Only a salon interview', 'A school spelling test', 'A product-brand exam'],
    answer: 0,
    explanation: 'Nebraska DHHS states that applicants for an initial cosmetology license must take the NIC written examination.',
    difficulty: 'Nebraska',
  },
  {
    id: 36,
    topic: 'nebraska',
    prompt: 'What type of cosmetology examination does Nebraska currently require for an initial license?',
    choices: ['A hands-on practical exam only', 'A written exam with no hands-on practical exam', 'A makeup portfolio review', 'A business tax exam'],
    answer: 1,
    explanation: 'The current DHHS examination page says Nebraska requires the NIC written exam and does not require a hands-on practical exam.',
    difficulty: 'Nebraska',
  },
  {
    id: 37,
    topic: 'nebraska',
    prompt: 'Which company administers Nebraska cosmetology examinations?',
    choices: ['PSI', 'A local salon', 'The product manufacturer', 'The school bookstore'],
    answer: 0,
    explanation: 'Nebraska DHHS identifies PSI as the company that administers the computer-based examination.',
    difficulty: 'Nebraska',
  },
  {
    id: 38,
    topic: 'nebraska',
    prompt: 'In which language does Nebraska require the cosmetology examination to be administered?',
    choices: ['English', 'Any language chosen at the test center', 'Latin only', 'The client preferred language'],
    answer: 0,
    explanation: 'The current Nebraska DHHS examination information states that Nebraska requires the test to be administered in English.',
    difficulty: 'Nebraska',
  },
  {
    id: 39,
    topic: 'nebraska',
    prompt: 'What must an applicant submit before Nebraska DHHS authorizes the cosmetology examination?',
    choices: ['A complete license application', 'A retail sales receipt', 'A client review', 'A salon menu'],
    answer: 0,
    explanation: 'Nebraska DHHS says an applicant must submit a complete license application before applying for the examination.',
    difficulty: 'Nebraska',
  },
  {
    id: 40,
    topic: 'nebraska',
    prompt: 'Where should you verify current Nebraska cosmetology practice and sanitation rules?',
    choices: ['172 NAC 34, 36, and 37 and current DHHS guidance', 'An old study guide only', 'A social media comment', 'A product advertisement'],
    answer: 0,
    explanation: 'DHHS points applicants to current Nebraska regulations, including sanitation and safety, practice, and school rules. Always verify the current text before testing.',
    difficulty: 'Nebraska',
  },
];

const generatedQuestionTemplates = {
  sanitation: [
    ['clean implements', 'Remove visible debris before disinfection', 'Store used tools with clean tools', 'Skip the product label'],
    ['disinfectant contact time', 'Keep the surface wet for the label time', 'Rinse immediately', 'Use a shorter time'],
    ['single-use items', 'Discard porous items after use', 'Put porous items in a UV box', 'Share them between clients'],
    ['hand hygiene', 'Wash hands before and after each service', 'Wash only at closing', 'Use lotion instead'],
    ['clean storage', 'Keep disinfected tools in a clean, covered container', 'Leave them on the floor', 'Store them beside used tools'],
    ['laundry', 'Place used linens in a closed container', 'Shake them near clean towels', 'Reuse them if dry'],
    ['blood exposure', 'Stop the service and follow the exposure procedure', 'Continue without gloves', 'Hide the area'],
    ['work surfaces', 'Clean and disinfect the surface between clients', 'Disinfect once per week', 'Cover debris with a towel'],
    ['protective equipment', 'Use appropriate gloves when handling chemicals', 'Use bare hands', 'Wear gloves only for haircuts'],
    ['product labels', 'Follow the manufacturer instructions', 'Mix products by guesswork', 'Ignore warnings'],
    ['tool inspection', 'Remove damaged tools from service', 'Use them carefully anyway', 'Repair them during a service'],
    ['cross-contamination', 'Use a clean applicator for each client', 'Double-dip an applicator', 'Share open product'],
  ],
  hair: [
    ['the cortex', 'It gives hair much of its strength and elasticity', 'It produces sweat', 'It forms the nail plate'],
    ['the cuticle', 'It protects the inner hair shaft', 'It creates the scalp', 'It produces sebum'],
    ['hair porosity', 'It describes how hair absorbs and retains moisture', 'It measures hair length', 'It identifies face shape'],
    ['hair density', 'It describes the number of hairs in an area', 'It describes curl size', 'It measures shampoo strength'],
    ['the consultation', 'It establishes goals and service history', 'It replaces sanitation', 'It guarantees a reference photo'],
    ['sectioning', 'It helps control and organize the service', 'It permanently changes texture', 'It disinfects the scalp'],
    ['elevation', 'It affects the weight and graduation of a haircut', 'It measures color level', 'It determines product pH'],
    ['a guide', 'It helps maintain a consistent haircut length', 'It removes dandruff', 'It replaces a comb'],
    ['thermal protection', 'It helps reduce heat-related damage', 'It makes heat harmless', 'It replaces a temperature check'],
    ['the medulla', 'It is the innermost layer when present', 'It is the outer scale layer', 'It is a skin gland'],
    ['the follicle', 'It is the tube-like structure that surrounds the root', 'It is the hair tip', 'It is a styling brush'],
    ['hair growth', 'It occurs in cycles', 'It occurs only during shampooing', 'It stops permanently after one haircut'],
  ],
  chemistry: [
    ['a strand test', 'It previews how hair may respond to a chemical service', 'It replaces every consultation', 'It measures scalp density'],
    ['a patch test', 'It checks for possible product sensitivity', 'It determines haircut length', 'It measures hair porosity'],
    ['developer', 'It supplies oxidation for many color formulas', 'It is a finishing spray', 'It removes all pigment alone'],
    ['neutralizer', 'It stabilizes bonds after a permanent wave', 'It cleans the workstation', 'It lightens every hair color'],
    ['product pH', 'It describes how acidic or alkaline a product is', 'It measures hair density', 'It predicts haircut shape'],
    ['chemical burns', 'They require stopping and following safety directions', 'They should be covered with color', 'They are normal processing'],
    ['chemical storage', 'Products should remain in labeled containers', 'Products should be stored unlabeled', 'Products should be mixed in advance'],
    ['manufacturer directions', 'They explain safe use and processing', 'They are optional suggestions', 'They apply only to shampoo'],
    ['oxidation', 'It is involved in many permanent color processes', 'It means brushing hair', 'It is a type of haircut'],
    ['a relaxer', 'It permanently changes the natural curl pattern', 'It only adds temporary shine', 'It is a disinfectant'],
    ['a permanent wave', 'It restructures hair into a new wave pattern', 'It only removes surface oil', 'It is a nail service'],
    ['a formula record', 'It helps repeat and evaluate a chemical service', 'It replaces a safety test', 'It prevents all color changes'],
  ],
  skin: [
    ['skin analysis', 'It helps identify skin type and service needs', 'It replaces cleansing', 'It diagnoses disease'],
    ['cleansing', 'It removes surface makeup, oil, and debris', 'It permanently closes pores', 'It replaces moisturizer'],
    ['sebum', 'It lubricates and helps protect skin and hair', 'It forms the nail plate', 'It is a disinfectant'],
    ['contraindications', 'They are conditions that may require changing or avoiding a service', 'They are product fragrances', 'They guarantee a result'],
    ['waxing safety', 'Avoid waxing broken or actively irritated skin', 'Wax every open wound', 'Wax over sunburn'],
    ['the nail matrix', 'It produces much of the nail plate', 'It is the free edge', 'It stores polish'],
    ['the nail plate', 'It is made primarily of hard keratinized cells', 'It is made of sebum', 'It is a muscle'],
    ['cuticle care', 'Use gentle techniques around living skin', 'Cut living tissue deeply', 'Use unclean tools'],
    ['eye protection', 'It helps keep facial products away from the eyes', 'It replaces a skin analysis', 'It increases product strength'],
    ['massage product', 'It provides appropriate slip for facial massage', 'It should always be a strong exfoliant', 'It replaces cleansing'],
    ['exfoliation', 'It removes some surface dead cells', 'It removes every skin layer', 'It replaces sunscreen'],
    ['infection concerns', 'They are a reason to postpone service and recommend evaluation', 'They should be covered with polish', 'They should be scrubbed aggressively'],
  ],
  nebraska: [
    ['official state sources', 'They are the best place to verify current requirements', 'Old social posts', 'Unverified flashcards'],
    ['rule review dates', 'They help identify information that may need updating', 'They change the correct answer', 'They replace source checking'],
    ['license requirements', 'They should be checked with the current licensing agency', 'They are set by product brands', 'They never change'],
    ['exam bulletins', 'They can contain current testing information', 'They are always outdated', 'They replace a license'],
    ['professional records', 'They help document service details and reactions', 'They are unnecessary for chemicals', 'They replace informed communication'],
    ['scope of practice', 'It describes services a license permits', 'It means any service is allowed', 'It only describes retail sales'],
    ['facility rules', 'They help keep the workplace compliant and safe', 'They apply only to clients', 'They replace sanitation'],
    ['renewal information', 'It should be verified through the official agency', 'It comes from random comments', 'It never has a deadline'],
    ['rule conflicts', 'The current official rule should settle the conflict', 'The oldest guide wins', 'The longest answer wins'],
    ['continuing education', 'It can help practitioners keep current', 'It makes a license unnecessary', 'It prevents every complaint'],
    ['inspection readiness', 'Accurate records and clean practices are important', 'Hiding supplies is best', 'Labels are optional'],
    ['client protection', 'Following current rules supports safe professional services', 'Rules are only paperwork', 'Safety is optional'],
  ],
};

const questionStems = [
  'Which statement best describes',
  'What is the main reason to understand',
  'Which practice correctly relates to',
  'A cosmetologist should remember that',
  'What is the safest approach to',
  'Which answer best explains',
  'During a professional service, why is it important to know about',
  'What should a student recognize about',
  'Which choice shows proper knowledge of',
  'Why does',
  'What is a key point about',
  'Which statement about',
  'Before a service, what should be understood about',
  'What does good practice require for',
  'Which option is most accurate about',
  'What is the professional response concerning',
];

function createAdditionalQuestions() {
  const additionalQuestions = [];
  let id = questions.length + 1;

  Object.entries(generatedQuestionTemplates).forEach(([topic, concepts]) => {
    concepts.forEach(([subject, correctAnswer, ...wrongAnswers], conceptIndex) => {
      questionStems.forEach((stem, stemIndex) => {
        const answerIndex = stemIndex % 4;
        const choices = [...wrongAnswers, 'Use an unrelated service instead', correctAnswer];
        const correctChoice = choices.pop();
        choices.splice(answerIndex, 0, correctChoice);

        additionalQuestions.push({
          id,
          topic,
          prompt: `${stem} ${subject}?`,
          choices,
          answer: answerIndex,
          explanation: `${correctAnswer}. Always apply the relevant product directions, safety procedures, and current professional rules.`,
          difficulty: conceptIndex % 3 === 0 ? 'Core' : 'Review',
        });
        id += 1;
      });
    });
  });

  return additionalQuestions;
}

questions.push(...createAdditionalQuestions());
topics.forEach((topic) => {
  topic.count = questions.filter((question) => question.topic === topic.id).length;
});
